*** Variables ***

${lbl_result_listings}                           //android.widget.SeekBar//android.widget.TextView[@resource-id="x:id/page.listings.header.count.text"]
${pnl_first_residential}                         //android.view.ViewGroup[@resource-id="x:id/listing_browser.vertical.large_card.0"]
${lbl_residential_price}                         //android.widget.TextView[@resource-id="x:id/page.property_details.summary.sale_price"]
${lbl_residentail_bedroom}                       //android.widget.TextView[@resource-id="x:id/page.property_details.summary.bedrooms.value"]
${lbl_realtor_information}                       //android.widget.TextView[@resource-id="x:id/page.property_details.realtor_information.header"]
${lbl_name_salesperson}                          //android.widget.TextView[@resource-id="x:id/view.realtor_information.card.interested"]/following-sibling::android.view.ViewGroup/android.view.ViewGroup/android.widget.TextView
${btn_get_in_touch}                              //android.widget.Button[@content-desc="Get in touch!"]
${lbl_phone_number}                              //android.widget.TextView[@resource-id="x:id/view.realtor_information.card.realtor.phone.text"]